trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  # Emulate `npm ci` as closely as possible with yarn.
  # @see https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-frozen-lockfile
  - script: yarn install --frozen-lockfile
    displayName: "install Node.js dependencies"

  - script: |
      echo "##vso[task.setvariable variable=POTATO]p_o_t_a_t_o"
      echo $(POTATO)
    displayName: "set up variable"
    env:
      BRANCH_NAME: $(Build.SourceBranchName)

  - script: yarn build
    displayName: "build application"
    env:
      BRANCH_NAME: $(Build.SourceBranchName)

  - publish: ./dist
    artifact: dist_build_artifact
    displayName: "publish application"
